In [ ]:
from pathlib import Path
import json
from collections import defaultdict, Counter

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from IPython.display import display

## SamplePairs

In [ ]:
dir_samplepairs = Path('/projects/mtg/projects/sample-identification/datasets/samplepairs_withnoise')

path_csv_samplepairs = dir_samplepairs / 'meta' / 'samples.csv'
path_tsv_samplepairs = dir_samplepairs / 'meta' / 'metadata.tsv'

In [ ]:
df_samplepairs = pd.read_csv(path_csv_samplepairs, delimiter=',')

with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(df_samplepairs)

In [ ]:
sources = set(df_samples['original_track_id'].str.strip())
receivers = set(df_samples['sample_track_id'].str.strip())
both = sources & receivers
print(both)

In [7]:
# Rows where the pair appears more than once (keeps all occurrences)
dupes = df_samples[
    df_samples.duplicated(subset=['original_track_id', 'sample_track_id'], keep=False)
].sort_values(['original_track_id', 'sample_track_id'])
display(dupes)

Empty DataFrame
Columns: [sample_track_id, original_track_id]
Index: []

In [9]:
# Why are there duplicates?
edges = df_samples[['original_track_id', 'sample_track_id']].drop_duplicates()
print(len(edges))

102

In [ ]:
1258904

In [9]:
df_samplepairs_metadata = pd.read_csv(path_tsv_samplepairs, sep='\t', encoding='latin-1')
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(df_samplepairs_metadata)

,PairID,ID1,YTLink1,Artist1,Title1,Year1,Start1,ID2,YTLink2,Artist2,Title2,Year2,Start2,Website
0,1,1,https://www.youtube.com/watch?v=6jgBcsRCqI8,Berlioz,Something will happen,2024,0:20,2,https://www.youtube.com/watch?v=1dSRzxg7p1E,Willem Dafoe,Abandon perfection: try to fail,2020,0:15,https://www.whosampled.com/sample/1178057/Berlioz-Something-Will-Happen-Willem-Dafoe-Theoffcamerashow-Abandon-Perfection%3A-Try-to-Fail/
1,2,3,https://www.youtube.com/watch?v=N9bKBAA22Go,Future and Metro Boomin feat. Kendrick Lamar,Like that,2024,1:06,4,https://www.youtube.com/watch?v=kdf_GIV9Svo,Eazy-E,Eazy-Duz-It,1988,0:00,https://www.whosampled.com/sample/1158521/Future-Metro-Boomin-Kendrick-Lamar-Like-That-Eazy-E-Eazy-Duz-It/
2,3,5,https://www.youtube.com/watch?v=xeKSdJqFM6o,Jamie xx feat. Honey Dijon,Baddy on the Floor,2024,0:11,6,https://www.youtube.com/watch?v=UXBIrO-VlSM,Keni Burke,Let Somebody Love You,1981,0:01,https://www.whosampled.com/sample/1167203/Jamie-xx-Honey-Dijon-Baddy-on-the-Floor-Keni-Burke-Let-Somebody-Love-You/
3,4,7,https://www.youtube.com/watch?v=U8QhB8_0t2g,Benson Boone,Mystical Magical,2025,0:56,8,https://www.youtube.com/watch?v=vWz9VN40nCA,Olivia Newton-John,Physical,1981,0:46,https://www.whosampled.com/sample/1285693/Benson-Boone-Mystical-Magical-Olivia-Newton-John-Physical/
4,5,9,https://www.youtube.com/watch?v=h1AM48ZpSnw,Dennis DJ and Lusa Sonza,Motinha 2.0 (Mete Marcha),2025,0:30,10,https://www.youtube.com/watch?v=yU8IZ1gBwBU,MC Beth,Dana Da Motinha,2001,0:05,https://www.whosampled.com/sample/1258904/Dennis-DJ-Lu%C3%ADsa-Sonza-Motinha-2.0-(Mete-Marcha)-MC-Beth-Dan%C3%A7a-Da-Motinha/
5,6,11,https://www.youtube.com/watch?v=iD__IJWqwY8,YG Marley,Praise Jah in the Moonlight,2023,0:00,12,https://www.youtube.com/watch?v=a_O1kI6B9Bc,Bob Marley and The Wailers,Crisis,1978,0:16,https://www.whosampled.com/sample/1136450/YG-Marley-Praise-Jah-in-the-Moonlight-Bob-Marley-The-Wailers-Crisis/
6,7,13,https://www.youtube.com/watch?v=MEv4Hzf8Hhw,Morgan Wallen,Everything I Love,2023,0:28,14,https://www.youtube.com/watch?v=CoCaPJWqa28,The Allman Brothers Band,Midnight Rider,1970,0:24,https://www.whosampled.com/sample/1028230/Morgan-Wallen-Everything-I-Love-The-Allman-Brothers-Band-Midnight-Rider/
7,8,15,https://www.youtube.com/watch?v=421w1j87fEM,Burna Boy,Last Last,2022,0:09,16,https://www.youtube.com/watch?v=9_hKXk2qSuw,Toni Braxton,He Wasn't Man Enough,2000,0:14,https://www.whosampled.com/sample/942772/Burna-Boy-Last-Last-Toni-Braxton-He-Wasn%27t-Man-Enough/
8,9,17,https://www.youtube.com/watch?v=f36toA5VsoA,Playboi Carti,OPM BABI,2025,0:00,18,https://www.youtube.com/watch?v=hQOTdhuLBK8,Sample Magic,RSS2_75_vinyl_loop_holdon_F#maj,2022,0:00,https://www.whosampled.com/sample/1272964/Playboi-Carti-OPM-BABI-Sample-Magic-RSS2-75-vinyl-loop-holdon-F%23maj/
9,10,19,https://www.youtube.com/watch?v=r6glBvXN6H0,2Cellos,Sweet Child O'Mine,2021,0:03,20,https://www.youtube.com/watch?v=S6yuR8efotI,Johann Sebastian Bach,"Cello Suite No. 1 Prelude in G-Majeur, BWV 1007",1720,0:00,"https://www.whosampled.com/sample/918113/2Cellos-Sweet-Child-O%27-Mine-Johann-Sebastian-Bach-Cello-Suite-No.-1-Prelude-in-G-Majeur,-BWV-1007/"
10,11,21,https://www.youtube.com/watch?v=AxE6wEuLHQ0,Drake,Champagne Poetry,2021,2:26,22,https://www.youtube.com/watch?v=Q7vn-jG86l4,The Gabriel Hardeman Delegation,Until I Found the Lord (My Soul Couldn't Rest),1976,1:31,https://www.whosampled.com/sample/873084/Drake-Champagne-Poetry-The-Gabriel-Hardeman-Delegation-Until-I-Found-the-Lord-(My-Soul-Couldn%27t-Rest)/
11,12,23,https://www.youtube.com/watch?v=wNMZRTROYuw,Sigala and James Arthur,Lasting Lover,2020,0:00,24,https://www.youtube.com/watch?v=B9dSYgd5Elk,MGMT,Time to pretend,2007,0:17,https://www.whosampled.com/sample/773975/Sigala-James-Arthur-Lasting-Lover-MGMT-Time-to-Pretend/
12,13,25,https://www.youtube.com/watch?v=BC19kwABFwc,Dua Lipa,Love Again,2020,0:31,26,https://www.youtube.com/watch?v=PtJDq7f_EF0,Lew Stone & the Monseigneur Band feat. Al Bowlly,My Woman,1932,0:00,https://www.whosampled.com/sample/729975/Dua-Lipa-Love-Again-Lew-Stone-%26-the-Monseigneur-Band-Al-Bowlly-My-Woman/
13,14,27,https://www.youtube.com/watch?v=Gb76TgCUqAY,"Tyler, the Creator",ARE WE STILL FRIENDS?,2019,0:01,28,https://www.youtube.com/watch?v=2T57PF55qoI,Al Green,Dream,1977,1:45,"https://www.whosampled.com/sample/648348/Tyler,-the-Creator-ARE-WE-STILL-FRIENDS%3F-Al-Green-Dream/"
14,15,29,https://www.youtube.com/watch?v=VponTolIydo,Four50 and Big Yaya,Orange Chicken,2024,0:00,30,https://www.youtube.com/watch?v=YHJp4LpQaFY,Cotonete and Di Melo,Papos Desconexos (Pt. 1),2019,0:17,https://www.whosampled.com/sample/1244652/Four50-Big-Yaya-Orange-Chicken-Cotonete-Di-Melo-Papos-Desconexos-(Pt.-1)/
15,16,31,https://www.youtube.com/watch?v=cL3ypGWhcOQ,Bad Bunny feat. El Alfa,La Romana,2018,0:00,32,https://www.youtube.com/watch?v=HakFFSDlbYw,Leonardo Paniagua,Fue De Los Dos,1998,0:02,https://www.whosampled.com/sample/618470/Bad-Bunny-El-Alfa-La-Romana-Leonardo-Paniagua-Fue-De-Los-Dos/
16,17,33,https://www.youtube.com/watch?v=9MJr4BnO-g4,Fleet Foxes,On Another Ocean (January / June),2017,4:15,34,https://www.youtube.com/watch?v=Wy-v-FgiUD8,Mulatu Astatke,Tezeta (Nostalgia),1969,0:06,https://www.whosampled.com/sample/507393/Fleet-Foxes-On-Another-Ocean-(January-June)-Mulatu-Astatke-Tezeta-(Nostalgia)/
17,18,35,https://www.youtube.com/watch?v=_P7S2lKif-A,MC Fioti,Bum Bum Tam Tam,2017,0:01,36,https://www.youtube.com/watch?v=Datoqxx-biw,Johann Sebastian Bach,"Partita in a Minor for Solo Flute, BWV 1013",1722,0:22,"https://www.whosampled.com/sample/525179/MC-Fioti-Bum-Bum-Tam-Tam-Johann-Sebastian-Bach-Partita-in-a-Minor-for-Solo-Flute,-BWV-1013/"
18,19,37,https://www.youtube.com/watch?v=NnMuFqsmYSE,Kanye West feat. Kendrick Lamar,No More Parties in L.A.,2016,0:14,38,https://www.youtube.com/watch?v=YACa9jmpmc0,Junie Morrison,Suzie Thundertussy,1976,0:20,https://www.whosampled.com/sample/401053/Kanye-West-Kendrick-Lamar-No-More-Parties-in-L.A.-Junie-Morrison-Suzie-Thundertussy/
19,20,39,https://www.youtube.com/watch?v=eu0KsZ_MVBc,The Avalanches feat. Camp Lo,Because I'm Me,2016,1:11,40,https://www.youtube.com/watch?v=ZHRnLmsjex0,Six Boys in Trouble,Why Can't I Get It Too,1959,0:16,https://www.whosampled.com/sample/436053/The-Avalanches-Camp-Lo-Because-I%27m-Me-Six-Boys-in-Trouble-Why-Can%27t-I-Get-It-Too/
20,21,41,https://www.youtube.com/watch?v=hyiku5iCJeU,XXXTENTACION,Let's Pretend Were Numb,2015,0:00,42,https://www.youtube.com/watch?v=8hTKHS3wOgY,Yuna,Someone Out of Town,2011,0:00,https://www.whosampled.com/sample/485605/XXXTENTACION-Let%27s-Pretend-Were-Numb-Yuna-Someone-Out-of-Town/
21,22,43,https://www.youtube.com/watch?v=GNCd_ERZvZM,Thundercat,Them Changes,2015,0:00,44,https://www.youtube.com/watch?v=WRWtvbyprgo,The Isley Brothers,Footsteps in the Dark,1977,0:00,https://www.whosampled.com/sample/358658/Thundercat-Them-Changes-The-Isley-Brothers-Footsteps-in-the-Dark/
22,23,45,https://www.youtube.com/watch?v=ooJiCv4ALmo,Thievery Corporation feat. Lou Lou Ghelichkhani,No More Disguise,2014,0:00,46,https://www.youtube.com/watch?v=kWWJTjP-_64,John Barry,"Plenty, Then Tiffany",1971,1:02,"https://www.whosampled.com/sample/400226/Thievery-Corporation-Lou-Lou-Ghelichkhani-No-More-Disguise-John-Barry-Plenty,-Then-Tiffany/"
23,24,47,https://www.youtube.com/watch?v=5Z9t0VkxPCY,Major Lazer feat. Sean Paul,Come on to Me,2014,1:53,48,https://www.youtube.com/watch?v=XKCD99urScc,Willie Coln and Hector Lavoe,La Murga,1971,0:00,https://www.whosampled.com/sample/256763/Major-Lazer-Sean-Paul-Come-on-to-Me-Willie-Col%C3%B3n-Hector-Lavoe-La-Murga/
24,25,49,https://www.youtube.com/watch?v=igI0C53Mr9U,Mgarimbe,Sister Bethina,2013,0:02,50,https://www.youtube.com/watch?v=qTA0RuZoIxM,Aaliyah,Try Again,2000,0:01,https://www.whosampled.com/sample/718153/Mgarimbe-Sister-Bethina-Aaliyah-Try-Again/
25,26,51,https://www.youtube.com/watch?v=5N48IErOVP0,Yonosuke Kitamura,All Night Long,2012,1:22,52,https://www.youtube.com/watch?v=T5EOsc5_bvg,Samplephonics,95_E_Tenor_SP17,2012,0:00,https://www.whosampled.com/sample/552648/Yonosuke-Kitamura-All-Night-Long-Samplephonics-95-E-Tenor-SP17/
26,27,53,https://www.youtube.com/watch?v=3jRM45yO9Rg,Christopher Tyng,Futurama Theme (Extended 2012 Version),2012,0:24,54,https://www.youtube.com/watch?v=aiwA0JrGfjA,Futurama,Welcome to the World of Tomorrow,1999,0:00,https://www.whosampled.com/sample/401979/Christopher-Tyng-Futurama-Theme-(Extended-2012-Version)-Futurama-Welcome-to-the-World-of-Tomorrow/
27,28,55,https://www.youtube.com/watch?v=fbFnF-86eYs,Jay-Z and Kanye West,Niggas in Paris,2011,0:07,56,https://www.youtube.com/watch?v=JpYPoMZhdyU,Reverend W.A. Donaldson,Baptizing Scene,1960,0:04,https://www.whosampled.com/sample/109674/Jay-Z-Kanye-West-Niggas-in-Paris-Reverend-W.A.-Donaldson-Baptizing-Scene/
28,29,57,https://www.youtube.com/watch?v=Vr2SlG9i9b4,Freddie Joachim,Waves,2011,0:00,58,https://www.youtube.com/watch?v=5mqvomO7eO8,Monk Higgins feat. The Specialties,One Man Band (Plays All Alone),1974,2:14,https://www.whosampled.com/sample/186319/Freddie-Joachim-Waves-Monk-Higgins-The-Specialties-One-Man-Band-(Plays-All-Alone)/
29,30,59,https://www.youtube.com/watch?v=jgBWeoJdbhA,Maya Jane Coles,What They Say,2010,1:01,60,https://www.youtube.com/watch?v=CpMwbK9F8KY,Triple X,Feel the Same,1999,1:40,https://www.whosampled.com/sample/100414/Maya-Jane-Coles-What-They-Say-Triple-X-Feel-the-Same/
30,31,61,https://www.youtube.com/watch?v=Mxwr20HFQsA,Skrillex,My Name Is Skrillex,2010,1:30,62,https://www.youtube.com/watch?v=7j_yGYU_jUU,Andy Gibb,Shadow Dancing,1978,0:24,https://www.whosampled.com/sample/82884/Skrillex-My-Name-Is-Skrillex-Andy-Gibb-Shadow-Dancing/
31,32,63,https://www.youtube.com/watch?v=voBNpdXkLnU,The Prodigy,Warrior's Dance,2009,0:11,64,https://www.youtube.com/watch?v=pegKuWUR84Y,Eurythmics,Sweet Dreams (Nightmare Mix),1990,6:56,https://www.whosampled.com/sample/51540/The-Prodigy-Warrior%27s-Dance-Eurythmics-Sweet-Dreams-(Nightmare-Mix)/
32,33,65,https://www.youtube.com/watch?v=3ym_uuCWpzQ,Chronicle Grime,Career Cats Get Tiger Suits,2009,0:08,66,https://www.youtube.com/watch?v=1WvxTE08tHU,Michel Corringe,Cigarettes Sur Cigarettes,1969,0:03,https://www.whosampled.com/sample/1081378/Chronicle-Grime-Career-Cats-Get-Tiger-Suits-Michel-Corringe-Cigarettes-Sur-Cigarettes/
33,34,67,https://www.youtube.com/watch?v=kxSDM5glQyo,The Breakbeat Junkie,Here's a Funky Beat,2009,0:17,68,https://www.youtube.com/watch?v=87OkQYOMyZQ,Bob James,Shamboozie,1982,0:12,https://www.whosampled.com/sample/133240/The-Breakbeat-Junkie-Here%27s-a-Funky-Beat-Bob-James-Shamboozie/
34,35,69,https://www.youtube.com/watch?v=3bYeqY_GMKs,Gramatik,The Unfallen Kingdom,2009,0:00,70,https://www.youtube.com/watch?v=WW_KaxZ3AUg,Dom Salvador,Cantiga Por Luciana,1969,0:32,https://www.whosampled.com/sample/403692/Gramatik-The-Unfallen-Kingdom-Dom-Salvador-Cantiga-Por-Luciana/
35,36,71,https://www.youtube.com/watch?v=0RtYtIiVYpY,Cage the Elephant,Ain't No Rest for the Wicked (Wicked Devil Reggae Remix),2008,0:02,72,https://www.youtube.com/watch?v=rsYPeP1XJuM,Max Romeo,Chase the Devil,1976,0:00,https://www.whosampled.com/sample/7234/Cage-the-Elephant-Ain%27t-No-Rest-for-the-Wicked-(Wicked-Devil-Reggae-Remix)-Max-Romeo-Chase-the-Devil/
36,37,73,https://www.youtube.com/watch?v=nKv8Oyez_TQ,Mexican Institute of Sound,El Micrfono,2007,3:29,74,https://www.youtube.com/watch?v=bKjn26agAEs,Caf Tacuba,Chilanga Banda,1996,0:08,https://www.whosampled.com/sample/920101/Mexican-Institute-of-Sound-El-Micr%C3%B3fono-Caf%C3%A9-Tacuba-Chilanga-Banda/
37,38,75,https://www.youtube.com/watch?v=MxEjnYdfLXU,Kanye West,I Wonder,2007,0:00,76,https://www.youtube.com/watch?v=aBhBG5lqpzM,Labi Siffre,My Song,1972,0:45,https://www.whosampled.com/sample/262/Kanye-West-I-Wonder-Labi-Siffre-My-Song/
38,39,77,https://www.youtube.com/watch?v=Sk9XYQMRiLY,Pretty Lights,Finally Moving,2006,0:09,78,https://www.youtube.com/watch?v=BPjQ7iK5GVI,Etta James,Something's Got a Hold on Me,1962,0:01,https://www.whosampled.com/sample/38369/Pretty-Lights-Finally-Moving-Etta-James-Something%27s-Got-a-Hold-on-Me/
39,40,79,https://www.youtube.com/watch?v=EDwb9jOVRtU,Madonna,Hung up,2005,0:32,80,https://www.youtube.com/watch?v=XEjLoHdbVeE,ABBA,Gimme! Gimme! Gimme! (A Man After Midnight),1979,0:19,https://www.whosampled.com/sample/3/Madonna-Hung-Up-ABBA-Gimme!-Gimme!-Gimme!-(A-Man-After-Midnight)/
40,41,81,https://www.youtube.com/watch?v=ZtkNfC5Oymw,Kanye West feat. DJ Premier,Everything I Am,2007,0:01,82,https://www.youtube.com/watch?v=0StV8XtoO34,Prince Phillip Mitchell,If We Can't Be Lovers,2004,0:01,https://www.whosampled.com/sample/9670/Kanye-West-DJ-Premier-Everything-I-Am-Prince-Phillip-Mitchell-If-We-Can%27t-Be-Lovers/
41,42,83,https://www.youtube.com/watch?v=jCmbHWgkXek,Madlib,Mystic Bounce,2003,0:11,84,https://www.youtube.com/watch?v=VRVanOlsxzQ,Ronnie Foster,Mystic Brew,1972,0:01,https://www.whosampled.com/sample/34208/Madlib-Mystic-Bounce-Ronnie-Foster-Mystic-Brew/
42,43,85,https://www.youtube.com/watch?v=k0FmIMbSGbw,Sean Paul,Gimme the Light,2002,0:03,86,https://www.youtube.com/watch?v=VW8RT6lKQfY,Troyton Rami and Tony Kelly,Buzz Riddim,2001,0:03,https://www.whosampled.com/sample/91581/Sean-Paul-Gimme-the-Light-Troyton-Rami-Tony-Kelly-Buzz-Riddim/
43,44,87,https://www.youtube.com/watch?v=EA8RxRkNveM,Freddie Dredd,Cha Cha,2019,0:00,88,https://www.youtube.com/watch?v=Ayq1t6Q7hg8,Lisa Ono,"Sway It, Hula Girl",2001,0:14,"https://www.whosampled.com/sample/644908/Freddie-Dredd-Cha-Cha-Lisa-Ono-Sway-It,-Hula-Girl/"
44,45,89,https://www.youtube.com/watch?v=KyH9QTdR-88,Bebel Gilberto,Samba Da Beno,2000,0:00,90,https://www.youtube.com/watch?v=mwOuYoCoyaA,Amon Tobin,Nova,1998,0:00,https://www.whosampled.com/sample/1531/Bebel-Gilberto-Samba-Da-Ben%C3%A7%C3%A3o-Amon-Tobin-Nova/
45,46,91,https://www.youtube.com/watch?v=IO93qNxjoo0,NxxxxxS,What Did You Just Say,2016,0:00,92,https://www.youtube.com/watch?v=4DqPVakFkOw,Nobuo Uematsu,The Extreme,1999,0:27,https://www.whosampled.com/sample/559039/NxxxxxS-What-Did-You-Just-Say-Nobuo-Uematsu-The-Extreme/
46,47,93,https://www.youtube.com/watch?v=3eeIu7N7xS0,Tamia,So Into You,1998,0:23,94,https://www.youtube.com/watch?v=AM3arcIHcik,Commodores,Say Yeah,1978,0:30,https://www.whosampled.com/sample/603/Tamia-So-Into-You-Commodores-Say-Yeah/
47,48,95,https://www.youtube.com/watch?v=gUhRKVIjJtw,"The Notorious B.I.G. feat. Puff Daddy, Mase and Kelly Price",Mo Money Mo Problems,1997,0:40,96,https://www.youtube.com/watch?v=AGO19YOaw6U,Diana Ross,I'm Coming Out,1980,0:03,https://www.whosampled.com/sample/18/The-Notorious-B.I.G.-Puff-Daddy-Mase-Kelly-Price-Mo-Money-Mo-Problems-Diana-Ross-I%27m-Coming-Out/
48,49,97,https://www.youtube.com/watch?v=InFbBlpDTfQ,DJ Shadow,Midnight in a Perfect World,1996,0:10,98,https://www.youtube.com/watch?v=TYGaJr7G3Dc,Pekka Pohjola,The Madness Subsides,1975,0:00,https://www.whosampled.com/sample/2777/DJ-Shadow-Midnight-in-a-Perfect-World-Pekka-Pohjola-The-Madness-Subsides/
49,50,99,https://www.youtube.com/watch?v=mmi60Bd4jSs,Daft Punk,Da Funk,1995,0:11,100,https://www.youtube.com/watch?v=fwY4pKLKago,Vaughan Mason and Crew,"Bounce, Rock, Skate, Roll Pt. 2",1979,5:52,"https://www.whosampled.com/sample/579/Daft-Punk-Da-Funk-Vaughan-Mason-and-Crew-Bounce,-Rock,-Skate,-Roll-Pt.-2/"
50,51,101,https://www.youtube.com/watch?v=BTZAQlr6ZZc,Adam F,Circles,1995,0:07,102,https://www.youtube.com/watch?v=V56yeZtqQTs,Bob James,Westchester Lady,1976,0:09,https://www.whosampled.com/sample/503/Adam-F-Circles-Bob-James-Westchester-Lady/
51,52,103,https://www.youtube.com/watch?v=O7bXxoP0MtE,Chris Travis,Lights Off,2014,0:00,104,https://www.youtube.com/watch?v=SHAQlFq6TFg,George Michael,Fastlove,1996,0:00,https://www.whosampled.com/sample/258761/Chris-Travis-Lights-Off-George-Michael-Fastlove/
52,53,105,https://www.youtube.com/watch?v=rxgjPa1mu_s,Lil B,Is This Life,2013,0:00,106,https://www.youtube.com/watch?v=sRHBBy9mxHg,The Isley Brothers,Let's Lay Together,1996,0:00,https://www.whosampled.com/sample/1230013/Lil-B-Is-This-Life-The-Isley-Brothers-Let%27s-Lay-Together/
53,54,107,https://www.youtube.com/watch?v=LnKOxbwFAVs,Lil Baby,Humble,2020,0:00,108,https://www.youtube.com/watch?v=52PXsD5wET8,Lori Perri,Up Against the Wind,1996,1:17,https://www.whosampled.com/sample/741462/Lil-Baby-Humble-Lori-Perri-Up-Against-the-Wind/
54,55,109,https://www.youtube.com/watch?v=yoYZf-lBF_U,Mobb Deep,Shook Ones Part II,1996,0:05,110,https://www.youtube.com/watch?v=kuqR6EuvPhI,Quincy Jones,Kitty With the Bent Frame,1971,1:15,https://www.whosampled.com/sample/515/Mobb-Deep-Shook-Ones-Part-II-Quincy-Jones-Kitty-With-the-Bent-Frame/
55,56,111,https://www.youtube.com/watch?v=_JZom_gVfuw,The Notorious B.I.G. feat. Total,Juicy,1994,0:00,112,https://www.youtube.com/watch?v=9acYQyxL2qw,Mtume,Juicy Fruit (Fruity Instrumental Mix),1983,2:03,https://www.whosampled.com/sample/134/The-Notorious-B.I.G.-Total-Juicy-Mtume-Juicy-Fruit-(Fruity-Instrumental-Mix)/
56,57,113,https://www.youtube.com/watch?v=RijB8wnJCN0,Cypress Hill,Insane in the Brain,1993,0:04,114,https://www.youtube.com/watch?v=bs22HOEbTJY,Mel & Tim,Good Guys Only Win in the Movies,1969,0:02,https://www.whosampled.com/sample/854/Cypress-Hill-Insane-in-the-Brain-Mel-%26-Tim-Good-Guys-Only-Win-in-the-Movies/
57,58,115,https://www.youtube.com/watch?v=yyr2gEouEMM,Kendrick Lamar feat. Drake,Poetic Justice,2012,0:59,116,https://www.youtube.com/watch?v=7KcIAmqkXOU,Janet Jackson,"Any Time, Any Place",1993,4:10,"https://www.whosampled.com/sample/174851/Kendrick-Lamar-Drake-Poetic-Justice-Janet-Jackson-Any-Time,-Any-Place/"
58,59,117,https://www.youtube.com/watch?v=ZBBS4imv1qo,Major Lazer feat. J Balvin and El Alfa,Que Calor,2019,1:24,118,https://www.youtube.com/watch?v=w0-30EYdjgU,Loleatta Holloway,Crash Goes Love (Yell Apella),1992,0:54,https://www.whosampled.com/sample/678037/Major-Lazer-J-Balvin-El-Alfa-Qu%C3%A9-Calor-Loleatta-Holloway-Crash-Goes-Love-(Yell-Apella)/
59,60,119,https://www.youtube.com/watch?v=1AFN4dn09oM,Lionel Richie,My Destiny,1992,0:00,120,https://www.youtube.com/watch?v=ljzwabhHv0c,Lightnin' Rod feat. Kool & the Gang,Sport,1973,0:00,https://www.whosampled.com/sample/186252/Lionel-Richie-My-Destiny-Lightnin%27-Rod-Kool-%26-the-Gang-Sport/
60,61,121,https://www.youtube.com/watch?v=bAM1PEt7s30,Da Dysfunkshunal Familee,"Easy Come, Easy Go",2008,0:00,122,https://www.youtube.com/watch?v=eo7iwlMFPrM,Jamiroquai,When You Gonna Learn,1992,0:31,"https://www.whosampled.com/sample/152645/Da-Dysfunkshunal-Familee-Easy-Come,-Easy-Go-Jamiroquai-When-You-Gonna-Learn/"
61,62,123,https://www.youtube.com/watch?v=z6bICslpTfY,System X,Got to Believe,1994,1:09,124,https://www.youtube.com/watch?v=BblJR8WBlbw,Chic,Chic Mystique (Bonus Acappella),1992,1:03,https://www.whosampled.com/sample/259777/System-X-Got-to-Believe-Chic-Chic-Mystique-(Bonus-Acappella)/
62,63,125,https://www.youtube.com/watch?v=e5PnuIRnJW8,Nas,The World is Yours,1994,0:00,126,https://www.youtube.com/watch?v=fW8NQgqYoVQ,Ahmad Jamal Trio,I love music,1970,5:00,https://www.whosampled.com/sample/629/Nas-The-World-Is-Yours-Ahmad-Jamal-Trio-I-Love-Music/
63,64,127,https://www.youtube.com/watch?v=IMPr9XXGymA,Headie One feat. AJ Tracey and Stormzy,Ain't it different,2020,0:05,128,https://www.youtube.com/watch?v=3mjZ61IW-Nw,Red Hot Chili Peppers,Pretty Little Ditty,1989,2:02,https://www.whosampled.com/sample/771047/Headie-One-AJ-Tracey-Stormzy-Ain%27t-It-Different-Red-Hot-Chili-Peppers-Pretty-Little-Ditty/
64,65,129,https://www.youtube.com/watch?v=XTUbZx31_SA,Beastie Boys,Hey Ladies,1989,0:00,130,https://www.youtube.com/watch?v=iKvK5CasiZ0,Commodores,Machine Gun,1974,1:38,https://www.whosampled.com/sample/1457/Beastie-Boys-Hey-Ladies-Commodores-Machine-Gun/
65,66,131,https://www.youtube.com/watch?v=phOW-CZJWT0,Rob Base & DJ E-Z Rock,It Takes Two,1988,0:26,132,https://www.youtube.com/watch?v=Jiqxkdhzi_M,Lyn Collins,Think (About It),1972,1:23,https://www.whosampled.com/sample/539/Rob-Base-%26-DJ-E-Z-Rock-It-Takes-Two-Lyn-Collins-Think-(About-It)/

In [20]:
sample100_whosampled_ids = set(df_samplepairs_metadata["Website"].str.split("/sample/").str[1].str.split("/").str[0].to_list())
print(len(sample100_whosampled_ids))

103

In [23]:
"1258904" in sample100_whosampled_ids

True

In [22]:
samplepairs_yt_ids = df_samplepairs_metadata["YTLink1"].to_list() + df_samplepairs_metadata["YTLink2"].to_list()

samplepairs_yt_ids = set(url.split("/watch?v=")[1] for url in samplepairs_yt_ids)
print(len(samplepairs_yt_ids))

206

In [10]:
import csv
from collections import defaultdict

result = defaultdict(list)

with open(path_csv_samples, newline="", encoding='latin-1') as f:
    reader = csv.DictReader(f)
    for row in reader:
        result[row["sample_track_id"]].append(row["original_track_id"])
result = dict(result)

In [11]:
len(result)

102

In [12]:
max([len(v) for v in result.values()])

1

In [13]:
result

{'T001': ['T002'],
 'T003': ['T004'],
 'T005': ['T006'],
 'T007': ['T008'],
 'T009': ['T010'],
 'T011': ['T012'],
 'T013': ['T014'],
 'T015': ['T016'],
 'T017': ['T018'],
 'T019': ['T020'],
 'T021': ['T022'],
 'T023': ['T024'],
 'T025': ['T026'],
 'T027': ['T028'],
 'T029': ['T030'],
 'T031': ['T032'],
 'T033': ['T034'],
 'T035': ['T036'],
 'T037': ['T038'],
 'T039': ['T040'],
 'T041': ['T042'],
 'T043': ['T044'],
 'T045': ['T046'],
 'T047': ['T048'],
 'T049': ['T050'],
 'T051': ['T052'],
 'T053': ['T054'],
 'T055': ['T056'],
 'T057': ['T058'],
 'T059': ['T060'],
 'T061': ['T062'],
 'T063': ['T064'],
 'T065': ['T066'],
 'T067': ['T068'],
 'T069': ['T070'],
 'T071': ['T072'],
 'T073': ['T074'],
 'T075': ['T076'],
 'T077': ['T078'],
 'T079': ['T080'],
 'T081': ['T082'],
 'T083': ['T084'],
 'T085': ['T086'],
 'T087': ['T088'],
 'T089': ['T090'],
 'T091': ['T092'],
 'T093': ['T094'],
 'T095': ['T096'],
 'T097': ['T098'],
 'T099': ['T100'],
 'T101': ['T102'],
 'T103': ['T104'],
 'T105': ['T106'],
 'T107': ['T108'],
 'T109': ['T110'],
 'T111': ['T112'],
 'T113': ['T114'],
 'T115': ['T116'],
 'T117': ['T118'],
 'T119': ['T120'],
 'T121': ['T122'],
 'T123': ['T124'],
 'T125': ['T126'],
 'T127': ['T128'],
 'T129': ['T130'],
 'T131': ['T132'],
 'T133': ['T134'],
 'T135': ['T136'],
 'T137': ['T138'],
 'T139': ['T140'],
 'T141': ['T142'],
 'T143': ['T144'],
 'T145': ['T146'],
 'T147': ['T148'],
 'T149': ['T150'],
 'T151': ['T152'],
 'T153': ['T154'],
 'T155': ['T156'],
 'T157': ['T158'],
 'T159': ['T160'],
 'T161': ['T162'],
 'T163': ['T164'],
 'T165': ['T166'],
 'T167': ['T168'],
 'T169': ['T170'],
 'T171': ['T172'],
 'T173': ['T174'],
 'T175': ['T176'],
 'T177': ['T178'],
 'T179': ['T180'],
 'T181': ['T182'],
 'T183': ['T184'],
 'T185': ['T186'],
 'T187': ['T188'],
 'T189': ['T190'],
 'T191': ['T192'],
 'T193': ['T194'],
 'T195': ['T196'],
 'T199': ['T200'],
 'T201': ['T202'],
 'T203': ['T204'],
 'T205': ['T206']}